title: Marco Dorner - Tech Blog
description: Exploring Technology and Learning
author: Marco Dorner
email: marco.dorner@gmx.de

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Social media links
github_username: gitdorner